# Generated by Django 6.0.3 on 2026-04-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='secret',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='secret',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
