# Generated by Django 6.0.3 on 2026-04-21 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0002_rename_secret_value_encrypt_backfill'),
        ('vaults', '0002_secret_notes_secret_url_secret_username'),
    ]

    operations = [
    ]
