# Generated by Django 6.0.3 on 2026-04-21 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='accounts_ac_timesta_cc23ad_idx',
            old_name='accounts_ac_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='accounts_ac_user_id_efe7d1_idx',
            old_name='accounts_ac_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='accounts_ac_action_a00ee1_idx',
            old_name='accounts_ac_action_idx',
        ),
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='accounts_ac_resourc_11d942_idx',
            old_name='accounts_ac_resourc_idx',
        ),
    ]
